# Build RNN to generate hunger games sounding text

based on tutorial in here : https://www.tensorflow.org/text/tutorials/text_generation

Could not use all features since I have tf version 2.5

In [1]:
import sys, os
import tensorflow as tf
import pandas as pd
import numpy as np

Init Plugin
Init Graph Optimizer
Init Kernel


In [109]:
tf.__version__

'2.5.0'

In [5]:
with open("(1) The Hunger Games.txt", 'rb') as file : 
    txt_file = file.readlines()
type(txt_file)

list

In [11]:
len(txt_file)

1071

In [25]:
txt_all = [str(x)[2:] for x in txt_file][1:]
txt_all_long = [x.replace('\\r','\\s').replace('\\n','\\s') 
                for x in txt_all if len(x) > 49]

487

In [34]:
single_text = ' '.join(txt_all_long)
vocab = sorted(set(single_text))
len(vocab)

74

In [36]:
in_size, out_size = 200, 100
def split_input_sequence(seq) : 
    """
    split sequence into all but last & all but first
    """
    input_text = seq[:-1]
    output_text = seq[1:]
    return input_text, output_text


In [43]:
uc_split = tf.strings.unicode_split(single_text, input_encoding='UTF-8')
data = tf.data.Dataset.from_tensor_slices(uc_split)

In [88]:
vocab_lookup = {str(x):i for i,x in enumerate(list(vocab))}
letter_lookup = {i:str(x) for i,x in enumerate(list(vocab))}
uc_np = pd.Series(uc_split.numpy().astype(str)).astype(str).replace(vocab_lookup).values
tens = tf.convert_to_tensor(uc_np, dtype=tf.int64)

In [89]:
ids_dataset = tf.data.Dataset.from_tensor_slices(tens)

In [90]:
def translate(n) : 
    """
    translate
    """
    return letter_lookup[n]
for ids in ids_dataset.take(10):
    print(translate(ids.numpy()))

W
h
e
n
 
I
 
w
a
k


In [98]:
seq_length = 100
sequences = ids_dataset.batch(seq_length+1, drop_remainder=True)
for seq in sequences.take(1) : 
    print(seq)

tf.Tensor(
[44 55 52 61  0 30  0 70 48 58 52  0 68 63  5  0 67 55 52  0 62 67 55 52
 65  0 66 56 51 52  0 62 53  0 67 55 52  0 49 52 51  0 56 66  0 50 62 59
 51  7  0 34 72  0 53 56 61 54 52 65 66  0 66 67 65 52 67 50 55  0 62 68
 67  5  0 66 52 52 58 56 61 54  0 37 65 56 60 66  0 70 48 65 60 67 55  0
 49 68 67  0 53], shape=(101,), dtype=int64)


In [102]:
dataset = sequences.map(split_input_sequence)

for input_example, target_example in dataset.take(1):
    print("Input :", (input_example).numpy())
    print("Target:", (target_example).numpy())

Input : [44 55 52 61  0 30  0 70 48 58 52  0 68 63  5  0 67 55 52  0 62 67 55 52
 65  0 66 56 51 52  0 62 53  0 67 55 52  0 49 52 51  0 56 66  0 50 62 59
 51  7  0 34 72  0 53 56 61 54 52 65 66  0 66 67 65 52 67 50 55  0 62 68
 67  5  0 66 52 52 58 56 61 54  0 37 65 56 60 66  0 70 48 65 60 67 55  0
 49 68 67  0]
Target: [55 52 61  0 30  0 70 48 58 52  0 68 63  5  0 67 55 52  0 62 67 55 52 65
  0 66 56 51 52  0 62 53  0 67 55 52  0 49 52 51  0 56 66  0 50 62 59 51
  7  0 34 72  0 53 56 61 54 52 65 66  0 66 67 65 52 67 50 55  0 62 68 67
  5  0 66 52 52 58 56 61 54  0 37 65 56 60 66  0 70 48 65 60 67 55  0 49
 68 67  0 53]


2022-07-05 13:29:39.019665: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2022-07-05 13:29:39.021647: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


In [103]:
# Batch size
BATCH_SIZE = 64

# Buffer size to shuffle the dataset
# (TF data is designed to work with possibly infinite sequences,
# so it doesn't attempt to shuffle the entire sequence in memory. Instead,
# it maintains a buffer in which it shuffles elements).
BUFFER_SIZE = 10000

dataset = (
    dataset
    .shuffle(BUFFER_SIZE)
    .batch(BATCH_SIZE, drop_remainder=True)
    .prefetch(tf.data.experimental.AUTOTUNE))

dataset

<PrefetchDataset shapes: ((64, 100), (64, 100)), types: (tf.int64, tf.int64)>

In [199]:
# Length of the vocabulary in StringLookup Layer
vocab_size = len(vocab)

# The embedding dimension
embedding_dim = 128

# Number of RNN units
rnn_units = 256

class MyModel(tf.keras.Model):
    def __init__(self, vocab_size, embedding_dim, rnn_units):
        super().__init__(self)
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
        self.gru = tf.keras.layers.GRU(rnn_units,
                                       return_sequences=True,
                                       return_state=True)
        self.dense = tf.keras.layers.Dense(vocab_size)

    def call(self, inputs, states=None, return_state=False, training=False):
        x = inputs
        x = self.embedding(x, training=training)
        if states is None:
            states = self.gru.get_initial_state(x)
        x, states = self.gru(x, initial_state=states, training=training)
        x = self.dense(x, training=training)

        if return_state:
            return x, states
        else:
            return x

In [200]:
model = MyModel(
    vocab_size=vocab_size,
    embedding_dim=embedding_dim,
    rnn_units=rnn_units)

In [201]:
for input_example_batch, target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)
    print(example_batch_predictions.shape, "# (batch_size, sequence_length, vocab_size)")

(64, 100, 74) # (batch_size, sequence_length, vocab_size)


In [202]:
model.summary()

Model: "my_model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      multiple                  9472      
_________________________________________________________________
gru_4 (GRU)                  multiple                  296448    
_________________________________________________________________
dense_4 (Dense)              multiple                  19018     
Total params: 324,938
Trainable params: 324,938
Non-trainable params: 0
_________________________________________________________________


### Untrained model prediction

In [203]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
sampled_indices = tf.squeeze(sampled_indices, axis=-1).numpy()
sampled_indices

array([28, 10,  9, 14, 32, 64, 17, 24, 23, 27, 26, 69, 42, 60, 15, 35, 47,
       11, 51,  6, 45, 39,  8, 35, 35,  7, 20,  6, 47,  2,  3, 68, 55, 13,
       70, 41, 48, 63, 53, 24, 24, 52, 32, 58, 13, 29,  9, 50,  0, 14, 46,
       57,  5,  8, 45,  8, 36, 24, 17, 55, 49, 49, 61, 12, 61, 58, 64, 49,
       19, 57, 12, 50, 29, 51, 15, 41, 65, 26, 55, 25, 13, 24, 48, 55, 18,
       39, 32, 50,  0, 17, 51, 70, 43, 11, 38, 50,  1, 28, 41, 45])

In [204]:
def translate_array(arr) : 
    """
    translate over & over on an array
    """
    return np.array([translate(a) for a in arr])
def translate_array_join(arr) : 
    """
    join the text
    """
    return ''.join(translate_array(arr))

In [205]:
print("Input:\n", translate_array_join(input_example_batch[0].numpy()))
print()
print("Next Char Predictions:\n", translate_array_join(sampled_indices))

Input:
  The boy took one look back to the bakery as if checking that the coast was clear, then, his attenti

Next Char Predictions:
 G105Kq8CBFEvUm6N\2d-XR/NN.;-\"'uh4wTapfCCeKk4H0c 5Yj,/X/OC8hbbn3nkqb:j3cHd6TrEhD4Cah9RKc 8dwV2Qc!GTX


### Train model

In [ ]:
loss = tf.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer='adam', loss=loss)
EPOCHS = 55
# Directory where the checkpoints will be saved
checkpoint_dir = './training_checkpoints'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)

history = model.fit(dataset, epochs=EPOCHS, callbacks=[checkpoint_callback])

Epoch 1/55


2022-07-05 15:17:20.132125: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2022-07-05 15:17:20.474852: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2022-07-05 15:17:20.664091: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


80/80 [==============================] - 7s 60ms/step - loss: 1.5609
Epoch 2/55
80/80 [==============================] - 5s 61ms/step - loss: 1.5534
Epoch 3/55
80/80 [==============================] - 5s 60ms/step - loss: 1.5464
Epoch 4/55
80/80 [==============================] - 5s 60ms/step - loss: 1.5276
Epoch 5/55
80/80 [==============================] - 5s 60ms/step - loss: 1.5099
Epoch 6/55
80/80 [==============================] - 5s 61ms/step - loss: 1.4969
Epoch 7/55
80/80 [==============================] - 5s 63ms/step - loss: 1.4875
Epoch 8/55
80/80 [==============================] - 5s 62ms/step - loss: 1.4738
Epoch 9/55
80/80 [==============================] - 5s 62ms/step - loss: 1.4648
Epoch 10/55
80/80 [==============================] - 5s 60ms/step - loss: 1.4534
Epoch 11/55
80/80 [==============================] - 5s 59ms/step - loss: 1.4434
Epoch 12/55
80/80 [==============================] - 5s 60ms/step - loss: 1.4311
Epoch 13/55
80/80 [=============================

In [ ]:
x,y = model(inputs=tf.convert_to_tensor([[0,2,1]*30,[1,2]*45],dtype=tf.int64),states=None,return_state=True)
x.shape, y.shape

In [ ]:
translate_array_join(tf.squeeze(tf.random.categorical(x[:, -1, :], num_samples=1), axis=-1).numpy())

In [ ]:
def split_to_tens(split) : 
    """
    take unicode split array & turn to tensor
    """
    uc_np = pd.DataFrame(split.numpy().astype(str)).astype(str).replace(vocab_lookup).values
    tens = tf.convert_to_tensor(uc_np, dtype=tf.int64)
    return tens

In [ ]:
states = None
next_char = tf.constant(['Good morning puppy dog'])
result = [next_char]
for i in range(1000) : 
    nextchar = tf.strings.unicode_split(next_char, 'UTF-8')
    ids = split_to_tens(nextchar)
    logits, states = model(inputs=ids, states=states,return_state=True)
    predicted_logits = logits[:, -1, :]
    predicted_ids = tf.random.categorical(predicted_logits, num_samples=1)
    predicted_ids = tf.squeeze(predicted_ids, axis=-1).numpy()
    next_char = translate_array_join(predicted_ids)
    result.append(next_char)
results = tf.strings.join(result)
results

In [168]:
predicted_ids

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([0])>

# LSTM